"""Add txn_id to subscriber

Revision ID: b928a8d6e427
Revises: c5c65a538f12
Create Date: 2025-04-16 03:25:20.521699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b928a8d6e427'
down_revision = 'c5c65a538f12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscribers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('txn_id', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscribers', schema=None) as batch_op:
        batch_op.drop_column('txn_id')

    # ### end Alembic commands ###
