"""Initial migration

Revision ID: c5c65a538f12
Revises: 
Create Date: 2025-04-16 01:39:01.862416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5c65a538f12'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('call_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('called_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('community_owners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('community_name', sa.String(length=128), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('unique_link', sa.String(length=256), nullable=False),
    sa.Column('telegram_bot_username', sa.String(length=64), nullable=True),
    sa.Column('group_chat_id', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token'),
    sa.UniqueConstraint('unique_link')
    )
    op.create_table('alert_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('community_owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['community_owner_id'], ['community_owners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscribers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('payment_status', sa.String(length=32), nullable=True),
    sa.Column('payment_plan', sa.String(length=32), nullable=True),
    sa.Column('community_owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['community_owner_id'], ['community_owners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscribers')
    op.drop_table('alert_logs')
    op.drop_table('community_owners')
    op.drop_table('call_logs')
    # ### end Alembic commands ###
